name: Fetch TDI Facebook Feed

on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

permissions:
  # Required to commit and push the updated JSON file
  contents: write

jobs:
  fetch-tdi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          # Ensure compatibility with the script's features (import/fetch)
          node-version: "20"

      - name: Create data directory and initialize JSON if missing
        run: |
          # Ensure the directory structure exists
          mkdir -p assets/data
          # Initialize the file with a valid, empty JSON structure if it doesn't exist
          if [ ! -f assets/data/tdi_feed.json ]; then
            echo '{"generated_at":"2025-01-01T00:00:00Z","source":"init","page_id":"","post_count":0,"posts":[]}' > assets/data/tdi_feed.json
          fi

      - name: Run fetcher
        env:
          FB_PAGE_ACCESS_TOKEN: ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
        run: |
          # Use the correct path and file name for the script
          # Assumes the script is saved as scripts/tdi_fetch.js
          node scripts/tdi_fetch.js

      - name: Commit changes if any
        # Only commit if the fetcher generated a new file content
        run: |
          if git status --porcelain | grep -q "assets/data/tdi_feed.json"; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add assets/data/tdi_feed.json
            git commit -m "TDI feed update [skip ci]"
            # Use 'set-upstream' for the first push if the branch is new
            git push
          else
            echo "No changes to commit."
          fi
